---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-registry
  namespace: kio-stg
spec:
  encryptedData:
    .dockerconfigjson: AgCIaC2r3gfDxDjL/QfcpYgx+3p1Taehpq+ZkyXEeIJdR7EqOjLwUcrnat08/zfpx+9nh+h6jSBIQzq/wPu5OXeuYvGGfvu2mrtGYZcTbArC29J94VcDu3DQpZyGdUoQjV1PxPIvF41ueArpZfmTdIv5oQGo4HMQqEObddC0fMbnbs+3FU/sqYh+kxeS7xKwiV7Ngn0PFU0FfHDAFr55rM5VODPEeu36s4KkkpfUULEuXjSU3BrzrSqbWdkkyi7ZlOkq+fUARsBjz8mfXpghK5R4y8EMyqKdMU94cOJxd/8XRZeOXt037IZ8BkKYZQWJ7oLEBdAJxoxVXA7GiPIYwolQUfgU/olXoUI8Rz9YbMeme46AAFZSOiRk7t48e9Zm0TUN2GNDkNCrThnpCkwT7wGwbMognI95slD9H7QyFGCU09WBJuz0Ss0UT3L8eIDWYar08zmRUT6xkAmrudV/aFjKGk560/kd6qtZh1GzN5Hd9CyvWS/vfu56Ll+RQ++pYjJnK6oDneCH4k3zzT7dTjK1o9v4wElFvSbpwXL/drHbZxcMzppGrGUDnQF6MU3hBkj5OkV3gd05b4H0QA441RSBKhPL8r4771iyCqShb7TSP4Z8vY/CEWxMOVf23M4JTqpivOIVlg7NLu0HHxa16Tr2Vnl+7OlFUf9243bDlXzIHQqSocQ9jLZ9P/RjClkqWYLoKis+gQ1uExO+bY76Hy4XvPlJCuw8W6tWT5fqAaIlHrHOUCSFh3lakhiPeKcfhkwuEfOOj5i8P3uBDi9LEV5SHp/jxSZgZK1gQpmPeqgEMy/JLagTg4UE+DdeV4PahO9LwOclu8V0JQ8+Fc0m+NT4oOFeYsrukaWB0yhY7YvoputAWnzbSOIfzu4oa+rLkk28XPqh1KaCWCjsjpc1rGg/6VIXzdtTZBTRWWgQCwqwr/iI5StWQQBtDjMgrI4c
  template:
    metadata:
      name: harbor-registry
      namespace: kio-stg
    type: kubernetes.io/dockerconfigjson
