apiVersion: v1
kind: Service
metadata:
  name: kio-api-nodeport
spec:
  type: NodePort
  selector:
    app: kio-api
  ports:
    - name: api
      port: 8000
      targetPort: api
      nodePort: 30800
